export const CLEAR_MARKNOTES_REQUEST = 'CLEAR_MARKNOTES_REQUEST';
export const CLEAR_MARKNOTES_SUCCESS = 'CLEAR_MARKNOTES_SUCCESS';
export const CLEAR_MARKNOTES_FAILURE = 'CLEAR_MARKNOTES_FAILURE';

export const ADD_MARK_NOTE = 'ADD_MARK_NOTE';
